### ISSUE TITLE
Submit时报错：Invalid URL '': No scheme supplied

### ISSUE THREAD

**Issue by lixin-wei** [yuzeming/CEACStatTracker#3]
作者您好，我尝试flask启动你的app，但submit去咨询visa状态的时候，报如下错误，能请教下要怎么弄吗？
```python
-> % flask --app app run --host=0.0.0.0
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://11.124.135.146:5000
Press CTRL+C to quit
30.46.81.102 - - [07/Sep/2022 17:27:57] "GET / HTTP/1.1" 200 -
30.46.81.102 - - [07/Sep/2022 17:27:57] "GET /static/style.css HTTP/1.1" 304 -
30.46.81.102 - - [07/Sep/2022 17:27:57] "GET /static/qrcode.js HTTP/1.1" 304 -
30.46.81.102 - - [07/Sep/2022 17:27:57] "GET /stat.js HTTP/1.1" 200 -
[2022-09-07 17:28:03,349] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/admin/lianxin.wlx/CEACStatTracker/app.py", line 182, in index
    result = query_ceac_state_safe(location,case_no)
  File "/home/admin/lianxin.wlx/CEACStatTracker/tracker_remote.py", line 6, in query_ceac_state_safe
    req = requests.post(URL, json=[[loc,case_no]], timeout=100)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/home/admin/.pyenv/versions/3.7.11/lib/python3.7/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
30.46.81.102 - - [07/Sep/2022 17:28:03] "POST / HTTP/1.1" 500 -
```

我尝试自己debug了下，好像是因为这个URL是空的原因，请问这个URL要填什么呢？
```python
import requests

URL = ""

def query_ceac_state_safe(loc, case_no, soup=None):
    req = requests.post(URL, json=[[loc,case_no]], timeout=100)
    ret = req.json()
    return ret[case_no]


def query_ceac_state_remote(req_data):
    req = requests.post(URL, json=req_data, timeout=180)
    ret = req.json()
    return ret


if __name__ == "__main__":
    print(query_ceac_state_safe("BEJ","AA00A38G49"))
```

**Comment by yuzeming** [comment]
这个是serverless 探针的地址。有两个解决方法。
1  改称本地部署探针 注意由于境内访问国外查询的网站非常不稳定，可能导致网站卡住。

修改这两处地方
https://github.com/yuzeming/CEACStatTracker/blob/6a487817a9d6f67b5b9525869ab614eb88050b60/app.py#L11
https://github.com/yuzeming/CEACStatTracker/blob/6a487817a9d6f67b5b9525869ab614eb88050b60/app.py#L106-L114

2 用腾讯云的serverless 部署一下 CEAC-serverless文件夹下的内容，然后把api的地址填到这里。
